#!/bin/sh
# postrm script for phpmemcachedadmin

set -e

lighttpd_remove() {
	if [ -f /etc/lighttpd/conf-available/50-phpmemcachedadmin.conf ] ; then
		rm -f /etc/lighttpd/conf-available/50-phpmemcachedadmin.conf
		if which lighty-enable-mod >/dev/null 2>&1 ; then
			lighty-disable-mod phpmemcachedadmin
			# We also enabled auth in postinst, but I think it's safer to keep it there
		else
			echo "Lighttpd not installed, skipping"
		fi
		# See bug #448682
		if [ -h /etc/lighttpd/conf-enabled/50-phpmemcachedadmin.conf ] ; then
		    echo 'Manually deleting lighttpd/phpMemcachedAdmin configuration link'
		    rm /etc/lighttpd/conf-enabled/50-phpmemcachedadmin.conf
		fi
	fi
}

apache_remove() {
        COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
                . /usr/share/apache2/apache2-maintscript-helper
                apache2_invoke disconf phpmemcachedadmin
        elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
                rm -f /etc/apache2/conf.d/phpmemcachedadmin.conf
        fi

	rm -f /etc/apache2/conf-available/phpmemcachedadmin.conf
}
if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/phpmemcachedadmin/Memcache.php
    if which ucf >/dev/null 2>&1; then
	ucf --debconf-ok --purge /etc/phpmemcachedadmin/Memcache.php
    fi
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

	if [ -f /usr/share/debconf/confmodule ]; then
		db_version 2.0

		db_get phpmemcachedadmin/reconfigure-webserver

		webservers="$RET"

		for webserver in $webservers; do
			webserver=${webserver%,}
			if [ "$webserver" = "lighttpd" ] ; then
				lighttpd_remove
			else
				apache_remove $1
			fi
			# Redirection of 3 is needed because Debconf uses it and it might 
			# be inherited by webserver. See bug #446324.
			if [ -f /etc/init.d/$webserver ] ; then
				if [ -x /usr/sbin/invoke-rc.d ]; then
					invoke-rc.d $webserver reload 3>/dev/null || true
				else
					/etc/init.d/$webserver reload 3>/dev/null || true
				fi
			fi
		done
	fi


	if [ "$1" = "purge" ]; then
        # Possibly installed desktop file
        if [ -h /usr/share/applications/phpmemcachedadmin.desktop ] ; then
            rm -f /usr/share/applications/phpmemcachedadmin.desktop
        fi
        if [ -h /etc/avahi/services/phpmemcachedadmin.service ] ; then
            rm -f /etc/avahi/services/phpmemcachedadmin.service
        fi
		rm -rf /etc/phpmemcachedadmin /var/lib/phpmemcachedadmin
	fi
fi

#DEBHELPER#

exit 0
